// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBG03ug8zN7vWpjANCE9kYA3p7pIGNkUgM',
    appId: '1:29992406568:android:987c73ccac1df72d8a2f1d',
    messagingSenderId: '29992406568',
    projectId: 'mform-6aa5f',
    databaseURL: 'https://mform-6aa5f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mform-6aa5f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkVfDlS2J_NWTfzXe_nTbUz3W_su4EhKg',
    appId: '1:29992406568:ios:440db6e9350c476a8a2f1d',
    messagingSenderId: '29992406568',
    projectId: 'mform-6aa5f',
    databaseURL: 'https://mform-6aa5f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mform-6aa5f.firebasestorage.app',
    iosBundleId: 'com.example.m4mf',
  );
}
